import time
import os
play_one = str(input("PLAYER ONE: What is your name? "))
play_two = str(input("PLAYER TWO: What is your name? "))
os.system('cls')
time.sleep(1)
print("Thank you! Alright", play_one, "and", play_two, "let us begin!")
time.sleep(5)
os.system('cls')
sent_1 = str(input("Part 1/3 PLAYER ONE: Enter a sentence that ends with the word AND ... "))
os.system('cls')
sent_2 = str(input("Part 1/3 PLAYER TWO: Enter a sentence that ends with the word SO ... "))
os.system('cls')
sent_3 = str(input("Part 2/3 PLAYER ONE: Enter a sentence that ends with the word THEN ... "))
os.system('cls')
sent_4 = str(input("Part 2/3 PLAYER TWO: Enter a sentence that ends with the word BECAUSE ... "))
os.system('cls')
sent_5 = str(input("Part 3/3 PLAYER ONE: Enter a sentence that ends with the word AND ... "))
os.system('cls')
sent_6 = str(input("Part 3/3 PLAYER TWO: Enter a sentence to end your story ... "))
time.sleep(2)
os.system('cls')
print("PLEASE WAIT. THIS WILL BE GOOD!")
time.sleep(2)
os.system('cls')
print("THANK YOU FOR PLAYING. PLEASE ENJOY YOUR STORY BELOW!")
print(" ")
time.sleep(2)
print(sent_1)
print(sent_2)
print(sent_3)
print(sent_4)
print(sent_5)
print(sent_6)
time.sleep(2)
print(" ")
input("press the enter key to exit") 
